name: Build Docker Image

on:
  workflow_call:
    inputs:
      aws-region:
        required: true
        type: string
      ecr-repository:
        required: true
        type: string
      github-actions-role:
        required: true
        type: string
      image-tag:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  build-docker-image:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.github-actions-role }}
          aws-region: ${{ inputs.aws-region }}

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: docker build -t ${{ inputs.ecr-repository }} MailAnalyser/

      - name: Tag Docker image
        run: |
          docker tag mailanalyser ${{ steps.ecr-login.outputs.registry }}/${{ inputs.ecr-repository }}:${{ inputs.image-tag }}
          docker tag mailanalyser ${{ steps.ecr-login.outputs.registry }}/${{ inputs.ecr-repository }}:latest

      - name: Push Docker image to ECR
        run: |
          docker push ${{ steps.ecr-login.outputs.registry }}/${{ inputs.ecr-repository }}:${{ inputs.image-tag }}
          docker push ${{ steps.ecr-login.outputs.registry }}/${{ inputs.ecr-repository }}:latest
