name: Update Scheduled Task

on:
  workflow_call:
    inputs:
      aws-region:
        required: true
        type: string
      github-actions-role:
        required: true
        type: string
      task-definition-family:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  update-scheduled-task:
    runs-on: ubuntu-22.04

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.github-actions-role }}
          aws-region: ${{ inputs.aws-region }}

      - name: Download task definition
        run: >
          aws ecs describe-task-definition --task-definition ${{ inputs.task-definition-family }} --query taskDefinition
          > task-definition.json

      - name: Download event
        run: aws events list-targets-by-rule --rule ${{ inputs.task-definition-family }} > event.json

      - name: Update event
        run: |
          jq --arg newDefn "$(jq -r '.taskDefinitionArn' task-definition.json)" '.Targets[0].EcsParameters.TaskDefinitionArn = $newDefn' event.json > new-event.json
          aws events put-targets --rule ${{ inputs.task-definition-family }} --cli-input-json file://new-event.json
